ingestion_bucket_name: recover-ingestion
input_bucket_name: recover-input-data
template_bucket_name: recover-cloudformation
intermediate_bucket_name: recover-intermediate-data
processed_data_bucket_name: recover-processed-data
