template:
  path: glue-job-role.yaml
stack_name: glue-job-role
parameters:
  S3SourceBucketName: {{ stack_group_config.source_bucket }}
  S3IntermediateBucketName: !stack_output_external recover-intermediate-bucket::BucketName
  S3ParquetBucketName: !stack_output_external recover-processed-data-bucket::BucketName
  S3ArtifactBucketName: !stack_output_external recover-cloudformation-bucket::BucketName
stack_tags:
  {{ stack_group_config.default_stack_tags }}
