# This is the pre-ETL bucket (SYNAPSE_ATTACHED_BUCKET)
template:
  type: file
  path: s3-bucket.yaml
stack_name: recover-input-bucket
parameters:
  BucketName: {{ stack_group_config.input_bucket_name }}
stack_tags:
  {{ stack_group_config.default_stack_tags }}
