template:
  type: file
  path: s3-bucket.yaml
stack_name: recover-processed-data-bucket
dependencies:
  - prod/cfn-s3objects-macro.yaml
parameters:
  BucketName: {{ stack_group_config.processed_data_bucket_name }}
  SynapseIds: "3461799"
  OwnerTxtKeyPrefix: "{{ stack_group_config.namespace }}/parquet"
stack_tags:
  {{ stack_group_config.default_stack_tags }}
