template:
  type: file
  path: s3-bucket-html-hosting.yaml
stack_name: recover-shareable-artifacts-vpn-bucket
parameters:
  BucketName: {{ stack_group_config.shareable_artifacts_vpn_bucket_name }}
  EnableVpnAccess: "true"
stack_tags:
  {{ stack_group_config.default_stack_tags }}
