template:
  type: sam
  path: src/lambda_function/template.yaml
  artifact_bucket_name: !stack_output_external recover-cloudformation-bucket::BucketName
  artifact_prefix: 'recover/src/lambda'
dependencies:
  - prod/s3-to-glue-lambda-role.yaml
  - prod/glue-workflow.yaml
stack_name: '{{ stack_group_config.namespace }}-lambda-S3ToGlue'
stack_tags: {{ stack_group_config.default_stack_tags }}
parameters:
  S3ToGlueRoleArn: !stack_output_external s3-to-glue-lambda-role::RoleArn
  S3SourceBucketName: {{ stack_group_config.input_bucket_name }}
  PrimaryWorkflowName: !stack_output_external "{{ stack_group_config.namespace }}-glue-workflow::WorkflowName"
