template:
  path: s3-to-glue-lambda-role.yaml
stack_name: s3-to-glue-lambda-role
parameters:
  S3SourceBucketName: {{ stack_group_config.source_bucket }}
stack_tags:
  {{ stack_group_config.default_stack_tags }}
