template:
  type: sam
  path: src/lambda_function/template.yaml
  artifact_bucket_name: !stack_output_external recover-cloudformation-bucket
  artifact_prefix: 'recover/{{ stack_group_config.namespace }}/lambda'
dependencies:
  - prod/s3-to-glue-lambda-role.yaml
stack_name: '{{ stack_group_config.namespace }}-lambda-S3ToGlue'
stack_tags: {{ stack_group_config.default_stack_tags }}
parameters:
  Namespace: {{ stack_group_config.namespace }}
  S3ToGlueRoleArn: !stack_output_external s3-to-glue-lambda-role::RoleArn
