repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.29.0
    hooks:
      - id: yamllint
  - repo: https://github.com/awslabs/cfn-python-lint
    rev: v0.72.9
    hooks:
      - id: cfn-python-lint
        files: templates/.*\.(json|yml|yaml)$
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.1
    hooks:
      - id: remove-tabs
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
