FROM amazon/aws-glue-libs:glue_libs_3.0.0_image_01

# Update and install required tools
RUN yum update -y && yum install -y gcc make wget

# Download GLIBC source
RUN wget http://ftp.gnu.org/gnu/libc/glibc-2.28.tar.gz

# Extract GLIBC source
RUN tar -xzvf glibc-2.28.tar.gz

# Configure and install GLIBC
WORKDIR glibc-2.28
RUN mkdir build && cd build \
    && ../configure --prefix=/opt/glibc-2.28 \
    && make -j4 \
    && make install

# Set the new GLIBC in the environment
RUN echo "/opt/glibc-2.28/lib" > /etc/ld.so.conf.d/glibc-2.28.conf && ldconfig

# Set the new GLIBC in the environment
ENV LD_LIBRARY_PATH=/opt/glibc-2.28/lib:$LD_LIBRARY_PATH

# Verify GLIBC version
RUN ldd --version

RUN pip3 install moto~=4.1 datacompy~=0.8 pytest-datadir ecs_logging~=2.0 flask~=2.0 flask-cors~=3.0
ENTRYPOINT ["bash", "-l"]
