template:
  path: glue-job-S3ToJsonS3.yaml
dependencies:
  - develop/s3-intermediate-bucket.yaml
  - develop/s3-cloudformation-bucket.yaml
  - develop/glue-job-role.yaml
stack_name: "{{ stack_group_config.namespace }}-glue-job-S3ToJsonS3"
parameters:
  JobDescription: Sort JSON from ZIP archive into datasets
  JobRole: !stack_output_external glue-job-role::RoleArn
  TempS3Bucket: !stack_output_external recover-dev-intermediate-bucket::BucketName
  S3ScriptBucket: !stack_output_external recover-dev-cloudformation-bucket::BucketName
  S3ScriptKey: '{{ stack_group_config.namespace }}/recover/src/glue/jobs/s3_to_json.py'
  GluePythonShellVersion: "{{ stack_group_config.s3_to_json_python_shell_version }}"
  GlueVersion: "{{ stack_group_config.s3_to_json_glue_version }}"
stack_tags:
  {{ stack_group_config.default_stack_tags }}
