template:
  path: glue-tables.j2
stack_name: '{{ stack_group_config.namespace }}-glue-tables'
parameters:
  Namespace: {{ stack_group_config.namespace }}
  S3IntermediateBucketName: {{ stack_group_config.intermediate_bucket_name }}
stack_tags:
  {{ stack_group_config.default_stack_tags }}
sceptre_user_data:
  # this needs to be replaced with real versioned schemas
  dataset_schemas: !file src/glue/resources/table_columns.yaml
