template:
  path: glue-workflow.j2
stack_name: "{{ stack_group_config.namespace }}-glue-workflow"
dependencies:
  - develop/namespaced/glue-tables.yaml
  - develop/namespaced/glue-job-S3ToJsonS3.yaml
parameters:
  Namespace: {{ stack_group_config.namespace }}
  JsonBucketName: {{ stack_group_config.intermediate_bucket_name }}
  ParquetBucketName: {{ stack_group_config.processed_data_bucket_name }}
  GlueDatabase: !stack_output_external "{{ stack_group_config.namespace }}-glue-tables::DatabaseName"
  S3ToJsonJobName: !stack_output_external "{{ stack_group_config.namespace }}-glue-job-S3ToJsonS3::JobName"
  CompareParquetJobName: !stack_output_external "{{ stack_group_config.namespace }}-glue-job-CompareParquet::JobName"
  CompareParquetStagingNamespace: {{ stack_group_config.namespace }}
  CompareParquetMainNamespace: "main"
stack_tags:
  {{ stack_group_config.default_stack_tags }}
sceptre_user_data:
  dataset_schemas: !file src/glue/resources/table_columns.yaml
