template:
  path: lambda-raw-role.yaml
stack_name: "{{ stack_group_config.namespace }}-lambda-raw-role"
dependencies:
  - develop/namespaced/sns-dispatch.yaml
  - develop/namespaced/sqs-input-to-dispatch.yaml
  - develop/s3-cloudformation-bucket.yaml
  - develop/s3-input-bucket.yaml
  - develop/s3-raw-bucket.yaml
parameters:
  S3SourceBucketName: {{ stack_group_config.input_bucket_name }}
  S3TargetBucketName: {{ stack_group_config.raw_bucket_name }}
  SNSTopicArn: !stack_output_external "{{ stack_group_config.namespace }}-sns-dispatch::SnsTopicArn"
stack_tags:
  {{ stack_group_config.default_stack_tags }}
