template:
  path: lambda-s3-event-config-role.yaml
stack_name: "{{ stack_group_config.namespace }}-lambda-s3-event-config-role"
parameters:
  S3SourceBucketName: {{ stack_group_config.input_bucket_name }}
stack_tags:
  {{ stack_group_config.default_stack_tags }}
