template:
  path: s3-event-config-lambda-role.yaml
stack_name: "{{ stack_group_config.namespace }}-s3-event-config-lambda-role"
parameters:
  S3SourceBucketName: {{ stack_group_config.input_bucket_name }}
stack_tags:
  {{ stack_group_config.default_stack_tags }}
