template:
  type: file
  path: s3-owner-txt.yaml
stack_name: "{{ stack_group_config.namespace }}-recover-dev-input-bucket-owner-txt"
dependencies:
  - develop/cfn-s3objects-macro.yaml
  - develop/s3-input-bucket.yaml
parameters:
  BucketName: !stack_output_external recover-dev-input-bucket::BucketName
  SynapseIds: "3461799,3357179" # RecoverETL and meghasyam
  OwnerTxtKeyPrefix: {{ stack_group_config.namespace }}
