template:
  type: sam
  path: src/lambda_function/template.yaml
  artifact_bucket_name: !stack_output_external recover-dev-cloudformation-bucket::BucketName
  artifact_prefix: 'recover/{{ stack_group_config.namespace }}/lambda'
stack_name: '{{ stack_group_config.namespace }}-lambda-S3ToGlue'
stack_tags: {{ stack_group_config.default_stack_tags }}
parameters:
  Namespace: {{ stack_group_config.namespace }}
  S3SourceBucketName: recover-pilot-data
