template:
  path: sns-topic.yaml
stack_name: "{{ stack_group_config.namespace }}-sns-input-to-sqs"
parameters:
  S3SourceBucketArn: !stack_output_external recover-dev-input-bucket::BucketArn
stack_tags:
  {{ stack_group_config.default_stack_tags }}
