template:
  path: sns-topic.yaml
parameters:
  S3SourceBucketArn: !stack_output_external recover-dev-input-bucket::BucketArn
dependencies:
  - develop/s3-input-bucket.yaml
stack_name: "{{ stack_group_config.namespace }}-sns-input"
stack_tags:
  {{ stack_group_config.default_stack_tags }}
