template:
  path: glue-job-compare-parquet.j2
dependencies:
  - prod/glue-job-role.yaml
stack_name: "{{ stack_group_config.namespace }}-glue-job-CompareParquet"
parameters:
  Namespace: {{ stack_group_config.namespace }}
  JobDescription: Compares parquet datasets between two runs of the recover ETL
  JobRole: !stack_output_external glue-job-role::RoleArn
  TempS3Bucket: {{ stack_group_config.processed_data_bucket_name }}
  S3ScriptBucket: {{ stack_group_config.cloudformation_artifact_bucket_name }}
  S3ScriptKey: '{{ stack_group_config.namespace }}/src/glue/jobs/compare_parquet_datasets.py'
  GluePythonShellVersion: "{{ stack_group_config.glue_python_shell_python_version }}"
  GlueVersion: "{{ stack_group_config.glue_python_shell_glue_version }}"
  IsNamespaceDependent: "true"
stack_tags:
  {{ stack_group_config.default_stack_tags }}
sceptre_user_data:
  dataset_schemas: !file src/glue/resources/table_columns.yaml
