template:
  path: glue-job-JSONToParquet.j2
dependencies:
  - prod/glue-job-role.yaml
stack_name: '{{ stack_group_config.namespace }}-glue-job-JSONToParquet'
parameters:
  Namespace: {{ stack_group_config.namespace }}
  JobDescription: Export JSON datasets to Parquet
  JobRole: !stack_output_external glue-job-role::RoleArn
  TempS3Bucket: {{ stack_group_config.processed_data_bucket_name }}
  S3ScriptBucket: {{ stack_group_config.template_bucket_name }}
  S3ScriptKey: '{{ stack_group_config.namespace }}/src/glue/jobs/json_to_parquet.py'
  GlueVersion: "{{ stack_group_config.json_to_parquet_glue_version }}"
  AdditionalPythonModules: ecs_logging~=2.0
stack_tags:
  {{ stack_group_config.default_stack_tags }}
sceptre_user_data:
  dataset_schemas: !file src/glue/resources/table_columns.yaml
