template:
  type: sam
  path: src/lambda_function/s3_event_config/template.yaml
  artifact_bucket_name: {{ stack_group_config.template_bucket_name }}
  artifact_prefix: '{{ stack_group_config.namespace }}/src/lambda'
dependencies:
  - prod/namespaced/lambda-s3-event-config-role.yaml
  - prod/s3-cloudformation-bucket.yaml
  - prod/namespaced/sns-input.yaml
stack_name: '{{ stack_group_config.namespace }}-lambda-S3EventConfig'
stack_tags: {{ stack_group_config.default_stack_tags }}
parameters:
  Namespace: {{ stack_group_config.namespace }}
  S3ToGlueDestinationArn: !stack_output_external "{{ stack_group_config.namespace }}-sns-input::SnsTopicArn"
  S3ToGlueDestinationType: "Topic"
  S3EventConfigRoleArn: !stack_output_external "{{ stack_group_config.namespace }}-lambda-s3-event-config-role::RoleArn"
  S3SourceBucketName: {{ stack_group_config.input_bucket_name }}
