template:
  type: sam
  path: src/lambda_function/raw/template.yaml
  artifact_bucket_name: {{ stack_group_config.template_bucket_name }}
  artifact_prefix: "{{ stack_group_config.namespace }}/src/lambda"
dependencies:
  - prod/namespaced/lambda-raw-role.yaml
  - prod/namespaced/sqs-dispatch-to-raw.yaml
  - prod/s3-cloudformation-bucket.yaml
  - prod/s3-raw-bucket.yaml
stack_name: "{{ stack_group_config.namespace }}-lambda-raw"
parameters:
  RoleArn: !stack_output_external "{{ stack_group_config.namespace }}-lambda-raw-role::RoleArn"
  SQSQueueArn: !stack_output_external "{{ stack_group_config.namespace }}-sqs-dispatch-to-raw::PrimaryQueueArn"
  S3RawBucket: {{ stack_group_config.raw_bucket_name }}
  S3RawKeyPrefix: "{{ stack_group_config.namespace }}/json/"
stack_tags: {{ stack_group_config.default_stack_tags }}
