template:
  path: lambda-raw-role.yaml
stack_name: "{{ stack_group_config.namespace }}-lambda-raw-role"
dependencies:
  - prod/namespaced/sqs-dispatch-to-raw.yaml
  - prod/s3-cloudformation-bucket.yaml
  - prod/s3-raw-bucket.yaml
parameters:
  SQSQueueArn: !stack_output_external "{{ stack_group_config.namespace }}-sqs-dispatch-to-raw::PrimaryQueueArn"
  S3SourceBucketName: {{ stack_group_config.input_bucket_name }}
  S3TargetBucketName: {{ stack_group_config.raw_bucket_name }}
stack_tags:
  {{ stack_group_config.default_stack_tags }}
