template:
  type: sam
  path: src/lambda_function/s3_to_glue/template.yaml
  artifact_bucket_name: {{ stack_group_config.template_bucket_name }}
  artifact_prefix: '{{ stack_group_config.namespace }}/src/lambda'
dependencies:
  - prod/namespaced/s3-to-glue-lambda-role.yaml
  - prod/namespaced/glue-workflow.yaml
  - prod/namespaced/sqs-input-to-intermediate.yaml
stack_name: '{{ stack_group_config.namespace }}-lambda-S3ToGlue'
stack_tags: {{ stack_group_config.default_stack_tags }}
parameters:
  SQSQueueArn: !stack_output_external "{{ stack_group_config.namespace }}-sqs-input-to-intermediate::PrimaryQueueArn"
  S3ToGlueRoleArn: !stack_output_external "{{ stack_group_config.namespace }}-s3-to-glue-lambda-role::RoleArn"
  S3ToJsonWorkflowName: !stack_output_external "{{ stack_group_config.namespace }}-glue-workflow::S3ToJsonWorkflowName"
