template:
  path: sqs-queue.yaml
parameters:
  MessageRetentionPeriod: "1209600"
  ReceiveMessageWaitTimeSeconds: "20"
  VisibilityTimeout: "120"
  S3SourceBucketArn: !stack_output_external recover-raw-bucket::BucketArn
dependencies:
  - prod/s3-raw-bucket.yaml
stack_name: '{{ stack_group_config.namespace }}-sqs-input-to-raw'
stack_tags:
  {{ stack_group_config.default_stack_tags }}
