template:
  path: sqs-queue.yaml
parameters:
  MessageRetentionPeriod: "1209600"
  ReceiveMessageWaitTimeSeconds: "20"
  VisibilityTimeout: "900"
  SNSTopicSubscription: !stack_output_external "{{ stack_group_config.namespace }}-sns-dispatch::SnsTopicArn"
dependencies:
  - prod/namespaced/sns-dispatch.yaml
stack_name: "{{ stack_group_config.namespace }}-sqs-dispatch-to-raw"
stack_tags:
  {{ stack_group_config.default_stack_tags }}
