project_code: recover
namespace: {{ var.namespace | default('recover') }}
region: us-east-1
synapseAuthSsmParameterName: synapse-recover-auth
source_bucket: recover-s3-bucket-bucket-1rb2h1xfnxpoi
admincentral_cf_bucket: bootstrap-awss3cloudformationbucket-19qromfd235z9
default_stack_tags:
  Department: DNT
  Project: recover
  OwnerEmail: aws-recover-dev@sagebase.org
j2_environment:
  extensions:
    - jinja2.ext.do
    - jinja2.ext.debug
