project_code: recover
namespace: "{{ var.namespace | default('recover') }}"
region: us-east-1
synapseAuthSsmParameterName: synapse-recover-auth
source_bucket: recover-s3-bucket-bucket-1rb2h1xfnxpoi
admincentral_cf_bucket: bootstrap-awss3cloudformationbucket-19qromfd235z9
lambda_python_version: "3.9"
glue_python_shell_version: "3.9"
glue_version: "4.0"
pipenv_python_version: "3.9"
develop:
  aws_credentials_iam_role: arn:aws:iam::914833433684:role/sagebase-github-oidc-sage-bion-ProviderRolerecover-VTOKECAKJUBV
  cfn_bucket: recover-dev-cloudformation
prod:
  aws_credentials_iam_role: arn:aws:iam::659375444835:role/sagebase-github-oidc-sage-bion-ProviderRolerecover-1PV98HM269O8I
  cfn_bucket: recover-cloudformation
default_stack_tags:
  Department: DNT
  Project: recover
  OwnerEmail: aws-recover-dev@sagebase.org
j2_environment:
  extensions:
    - jinja2.ext.do
    - jinja2.ext.debug
