project_code: recover
latest_version: v0.1
region: us-east-1
synapseAuthSsmParameterName: synapse-recover-auth
default_stack_tags:
  Department: DNT
  Project: recover
  OwnerEmail: aws-recover-dev@sagebase.org
j2_environment:
  extensions:
    - jinja2.ext.do
    - jinja2.ext.debug
