project_code: recover
region: us-east-1
synapseAuthSsmParameterName: synapse-recover-auth
source_bucket: recover-s3-bucket-bucket-1rb2h1xfnxpoi
default_stack_tags:
  Department: DNT
  Project: recover
  OwnerEmail: aws-recover-dev@sagebase.org
j2_environment:
  extensions:
    - jinja2.ext.do
    - jinja2.ext.debug
