project_code: recover
namespace: {{ var.namespace | default('main') }}
region: us-east-1
synapseAuthSsmParameterName: synapse-recover-auth
admincentral_cf_bucket: bootstrap-awss3cloudformationbucket-19qromfd235z9
template_key_prefix: "{{ var.namespace | default('main') }}/templates"
glue_python_shell_python_version: "3.9"
glue_python_shell_glue_version: "3.0"
json_to_parquet_glue_version: "4.0"
default_stack_tags:
  Department: DNT
  Project: recover
  OwnerEmail: aws-recover-dev@sagebase.org
j2_environment:
  extensions:
    - jinja2.ext.do
    - jinja2.ext.debug
