template:
  type: file
  path: s3-bucket.yaml
stack_name: recover-dev-input-bucket
dependencies:
  - develop/cfn-s3objects-macro.yaml
parameters:
  BucketName: {{ stack_group_config.input_bucket_name }}
  SynapseIds: "3461799,3357179" # RecoverETL and meghasyam
  Namespace: {{ stack_group_config.namespace }}
