template:
  type: file
  path: s3-bucket.yaml
stack_name: recover-dev-input-bucket
parameters:
  BucketName: {{ stack_group_config.input_bucket_name }}
  ConnectToSynapse: "true"
stack_tags:
  {{ stack_group_config.default_stack_tags }}
