template:
  type: file
  path: s3-bucket.yaml
stack_name: recover-dev-processed-data-bucket
parameters:
  BucketName: {{ stack_group_config.processed_data_bucket_name }}
  ConnectToSynapse: "true"
stack_tags:
  {{ stack_group_config.default_stack_tags }}
