template:
  path: snowflake-s3-role.yaml
stack_name: snowflake-s3-role
parameters:
  S3SourceBucketName: {{ stack_group_config.input_bucket_name }}
  S3IntermediateBucketName: {{ stack_group_config.intermediate_bucket_name }}
  S3ParquetBucketName: {{ stack_group_config.processed_data_bucket_name }}
  AWSAccountId: "arn:aws:iam::637423216157:user/v93m0000-s"
  ExternalId: "0"
stack_tags:
  {{ stack_group_config.default_stack_tags }}
