AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Description: >
  SAM Template for s3-to-glue lambda function

Parameters:

  S3ToGlueRoleArn:
    Type: String
    Description: Arn for the S3 to Glue Lambda Role

  Namespace:
    Type: String
    Description: Namespace of the stack so that it may be unique

  Schedule:
    Description: >
      Schedule to execute the lambda function
    Type: String
    Default: cron(59 23 * * ? *)

Resources:
  S3ToGlueFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      CodeUri: ./s3_to_glue
      Handler: app.lambda_handler
      Runtime: python3.9
      Role: !Ref S3ToGlueRoleArn
      Timeout: 30
      Environment:
        Variables:
          NAMESPACE: !Ref Namespace
      Events:
        DailyTrigger:
          Type: Schedule
          Properties:
            Schedule: !Ref Schedule

Outputs:
  S3ToGlueFunctionArn:
    Description: Arn of the S3ToGlueFunction function
    Value: !GetAtt S3ToGlueFunction.Arn
    Export:
      Name: !Sub "${AWS::Region}-${AWS::StackName}-S3ToGlueFunctionArn"
