AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Description: >
  SAM Template for s3-to-glue lambda function

Parameters:

  S3ToGlueRoleArn:
    Type: String
    Description: Arn for the S3 to Glue Lambda Role

  PrimaryWorkflowName:
    Type: String
    Description: >
      Name of the main glue workflow that runs glue jobs from S3 to JSON and JSON to Parquet

  LambdaPythonVersion:
    Type: String
    Description: Python version to use for this lambda function
    Default: "3.9"


Resources:
  S3ToGlueFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      CodeUri: ./s3_to_glue
      Handler: app.lambda_handler
      Runtime: !Sub "python${LambdaPythonVersion}"
      Role: !Ref S3ToGlueRoleArn
      Timeout: 30
      Environment:
        Variables:
          PRIMARY_WORKFLOW_NAME: !Ref PrimaryWorkflowName

Outputs:
  S3ToGlueFunctionArn:
    Description: Arn of the S3ToGlueFunction function
    Value: !GetAtt S3ToGlueFunction.Arn
    Export:
      Name: !Sub "${AWS::Region}-${AWS::StackName}-S3ToGlueFunctionArn"
