AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Description: >
  An IAM Role for the S3 to JSON lambda

Parameters:
  S3SourceBucketName:
    Type: String
    Description: Name of the S3 bucket where source data are stored.

Resources:
  S3ToGlueRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
            - sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        Policies:
        - PolicyName: StartGlueWorkflow
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - glue:StartWorkflowRun
              - glue:PutWorkflowRunProperties
              Resource:
              - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:workflow/*
        - PolicyName: AccessS3BucketInputData
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
               - s3:Get*
               - s3:List*
              Resource:
              - !Sub arn:aws:s3:::${S3SourceBucketName}
              - !Sub arn:aws:s3:::${S3SourceBucketName}/*

Outputs:
  RoleName:
    Value: !Ref S3ToGlueRole
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-RoleName'

  RoleArn:
    Value: !GetAtt S3ToGlueRole.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-RoleArn'
