AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Creates a Standard SNS topic.

Resources:

  SnsTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: !Sub "${AWS::StackName}-Topic"
      FifoTopic: false

Outputs:

  SnsTopicArn:
    Value: !Ref SnsTopic
    Export:
      Name: !Sub "${AWS::Region}-${AWS::StackName}-SnsTopicArn"
