name: upload-and-deploy

on: [push]

jobs:

  pre-commit:

    name: Run pre-commit hooks against all files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: pre-commit/action@v3.0.0

  upload-files-branch:

    name: Upload files to S3 bucket in development
    runs-on: ubuntu-latest
    needs: pre-commit
    if: github.ref_name != 'main'
    permissions:
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
      id-token: write
      contents: read
    environment: develop
    uses: ./.github/workflows/action-pipenv-aws-setup.yaml
    with:
      python_version: '3.10'
      role_to_assume: ${{ vars.AWS_CREDENTIALS_IAM_ROLE }}
      cfn_bucket: ${{ vars.CFN_BUCKET }}


  upload-files-main:

    name: Upload files to S3 bucket in production
    runs-on: ubuntu-latest
    needs: pre-commit
    if: github.ref_name == 'main'
    permissions:
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
      id-token: write
      contents: read
    environment: develop
    uses: ./.github/workflows/action-pipenv-aws-setup.yaml
    with:
      python_version: '3.10'
      role_to_assume: ${{ vars.AWS_CREDENTIALS_IAM_ROLE }}
      cfn_bucket: ${{ vars.CFN_BUCKET }}
