name: upload-and-deploy

on: [push]

env:
  NAMESPACE: ${{ github.event.repository.name }}

jobs:

  pre-commit:

    name: Run pre-commit hooks against all files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: pre-commit/action@v3.0.0

  upload-files:

    name: Upload files to S3 bucket in development
    runs-on: ubuntu-latest
    needs: pre-commit
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    environment: develop
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pipenv
        shell: bash
        run: python -m pip install pipenv

      - name: Install dependencies
        env:
          PIPENV_NOSPIN: 'true'
        shell: bash
        run: |
          pipenv install --dev

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ vars.AWS_CREDENTIALS_IAM_ROLE }}
          role-session-name: GitHubActions-${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.run_id }}
          role-duration-seconds: 1200

      - name: Setup sam
        uses: aws-actions/setup-sam@v2

      - name: Set namespace for non-default branch
        if: github.ref_name != 'main'
        run: echo "NAMESPACE=$GITHUB_REF_NAME" >> $GITHUB_ENV

      - name: Copy files to namespaced templates bucket, use dev cloudformation bucket
        if: github.ref_name != 'main'
        run: python src/scripts/manage_artifacts/artifacts.py --upload --namespace $NAMESPACE --cfn_bucket ${{ vars.CFN_BUCKET }}

      - name: Copy files to non-namespaced templates bucket, use dev cloudformation bucket
        if: github.ref_name == 'main'
        run: python src/scripts/manage_artifacts/artifacts.py --upload --namespace '' --cfn_bucket ${{ vars.CFN_BUCKET }}


  sceptre-deploy-branch:

    name: Deploy branch using sceptre
    runs-on: ubuntu-latest
    needs: [pre-commit, upload-files]
    environment: develop
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Setup code, pipenv, aws
        uses: Sage-Bionetworks/action-pipenv-aws-setup@v3
        with:
          role-to-assume: ${{ vars.AWS_CREDENTIALS_IAM_ROLE }}
          role-session-name: GitHubActions-${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.run_id }}

      - name: Create directory for remote sceptre templates
        run: mkdir -p templates/remote/

      - name: Deploy namespaced sceptre stacks to dev
        if: github.ref_name != 'main'
        run: pipenv run sceptre --var "namespace=$GITHUB_REF_NAME" launch develop --yes

      - name: Deploy non-namespaced sceptre stacks to dev
        if: github.ref_name == 'main'
        run: pipenv run sceptre --var "namespace=$NAMESPACE" launch develop --yes
