name: Upload files workflow

description: >
  Common infrastructure setup which checks out code, sets up python, pipenv and sam,
  and assumes AWS IAM role with OIDC integration. This requires that the following environment variables are set up
  in your Github repository: for an IAM user, the role to assume as well as the artifact bucket name

inputs:

  python_version:
    description: version of python to use
    required: false
    default: 3.10

  role_to_assume:
    description: iam role assumed for deployments
    required: true

  cfn_bucket:
    description: name of cloudformation bucket to upload artifacts to
    required: true

runs:

  using: composite

  steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install pipenv
        shell: bash
        run: python -m pip install pipenv

      - name: Install dependencies
        env:
          PIPENV_NOSPIN: 'true'
        shell: bash
        run: |
          pipenv install --dev

      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ inputs.role_to_assume }}
          role-session-name: GitHubActions-${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.run_id }}
          role-duration-seconds: 1200

      - name: Setup sam
        uses: aws-actions/setup-sam@v2

      - name: Set namespace for non-default branch or for tag
        if: github.ref_name != 'main'
        run: echo "NAMESPACE=$GITHUB_REF_NAME" >> $GITHUB_ENV

      - name: Copy files to templates bucket, use dev cloudformation bucket
        if: github.ref_name != 'main'
        run: python src/scripts/manage_artifacts/artifacts.py --upload --namespace $NAMESPACE --cfn_bucket ${{ inputs.cfn_bucket }}

      - name: Copy files to templates dev bucket if main branch but don't add namespace
        if: github.ref_name == 'main'
        run: python src/scripts/manage_artifacts/artifacts.py --upload --namespace '' --cfn_bucket ${{ vars.cfn_bucket }}
